obj-$(CONFIG_LTN_DTV) += \
               bbm.o	\
               fc8101.o \
               fc8101_bb.o \
               fc8101_hpi.o \
               fc8101_isr.o \
               fc8101_ppi.o \
               fc8101_spi.o \
               fc8101_tun.o \
               fci_hal.o\
               fci_i2c.o \
               fci_oal.o \
               fci_ringbuffer.o \
               fci_tun.o         
          